development:
  host: localhost
  database: formulatron_app_development

test:
  host: localhost
  database: formulatron_app_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
